#▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖  ▗▄▄▖
#▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌  █    █ ▐▌ ▐▌▐▌ ▐▌▐▌   
#▐▌  ▐▌▐▌ ▐▌▐▌ ▝▜▌  █    █ ▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖
#▐▌  ▐▌▝▚▄▞▘▐▌  ▐▌▗▄█▄▖  █ ▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘
#

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=DP-3, 1920x1080@165,auto,1, vrr, 0, bitdepth, 10

# testing HDR settings

# monitor=DP-3, 1920x1080@165, 0x0,1, bitdepth, 10, cm, hdr, sdrbrightness,1.2, sdrsaturation,0.98
# monitor=DP-3, 1920x1080@165, 0x0,1, bitdepth, 10
#

monitorv2 {
  output = DP-3
  mode = 1920x1080@165
  position = 0x0
  scale = 1
  bitdepth = 10
  vrr = 1
  # # HDR/EDID overrides
  supports_wide_color = 1
  supports_hdr = 1
  sdrbrightness = 1.15
  sdrsaturation = 1.0
  sdr_min_luminance = 0.005
  sdr_max_luminance = 200
  min_luminance = 0
  max_luminance = 1000
  max_avg_luminance = 200
}

render:cm_auto_hdr=1
render:cm_fs_passthrough = 2

experimental {
  xx_color_management_v4 = true
}
