#▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖  ▗▄▄▖
#▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌  █    █ ▐▌ ▐▌▐▌ ▐▌▐▌   
#▐▌  ▐▌▐▌ ▐▌▐▌ ▝▜▌  █    █ ▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖
#▐▌  ▐▌▝▚▄▞▘▐▌  ▐▌▗▄█▄▖  █ ▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘
#

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-3, 1920x1080@165, 0x0,1, cm, auto, sdrbrightness,1.4, sdrsaturation,1.05

# testing HDR settings
#monitor=DP-3, 1920x1080@165, 0x0,1, bitdepth, 10, cm, hdr, sdrbrightness,1.4, sdrsaturation,1.05
#
experimental {
  xx_color_management_v4 = true
}
