# source = ~/.config/hypr/conf.d/animations/andriel.conf
# source = ~/.config/hypr/conf.d/animations/00-default.conf
# source = ~/.config/hypr/conf.d/animations/01-default - v2.conf
# source = ~/.config/hypr/conf.d/animations/END-4.conf
# source = ~/.config/hypr/conf.d/animations/HYDE - default.conf
# source = ~/.config/hypr/conf.d/animations/HYDE - Vertical.conf
# source = ~/.config/hypr/conf.d/animations/HYDE - minimal-1.conf
# source = ~/.config/hypr/conf.d/animations/HYDE - minimal-2.conf
source = ~/.config/hypr/conf.d/animations/HYDE - optimized.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - classic.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - dynamic.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - fast.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - high.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - moving.conf
# source = ~/.config/hypr/conf.d/animations/ML4W - standard.conf
# source = ~/.config/hypr/conf.d/animations/Mahaveer - me-1.conf
# source = ~/.config/hypr/conf.d/animations/Mahaveer - me-2.conf
# source = ~/.config/hypr/conf.d/animations/diablo-1.conf
# source = ~/.config/hypr/conf.d/animations/diablo-2.conf
 # source = ~/.config/hypr/conf.d/animations/theme.conf
# source = ~/.config/hypr/conf.d/animations/default.conf
