# ANDRIEL'S HYPRLAND CONFIG
source = ~/.config/hypr/scripts

# Modular config components
source = ~/.config/hypr/conf.d/01-monitors.conf
source = ~/.config/hypr/conf.d/02-autostart.conf
source = ~/.config/hypr/conf.d/03-environment.conf
source = ~/.config/hypr/conf.d/04-look-and-feel.conf
source = ~/.config/hypr/conf.d/05-input.conf
source = ~/.config/hypr/conf.d/06-rules.conf
source = ~/.config/hypr/conf.d/07-keybinding.conf
source = ~/.config/hypr/conf.d/08-animations.conf
# source = ~/.config/hypr/conf.d/09-plugins.conf

# set Scripts
$ScriptsPath = ~/.config/hypr/scripts
