[colors.primary]
background = '#303446'
foreground = '#c6d0f5'

[colors.selection]
text = '#c6d0f5'
background = '#243d6f'

[colors.cursor]
text = '#303446'
cursor = '#8caaee'

[colors.normal]
black   = '#292c3c'
red     = '#ff7299'
green   = '#77ee89'
yellow  = '#fff872'
blue    = '#7294e2'
magenta = '#243d6f'
cyan    = '#8caaee'
white   = '#eaeff9'

[colors.bright]
black   = '#5c5f65'
red     = '#ff9fb9'
green   = '#a5ffb3'
yellow  = '#fffaa5'
blue    = '#a5c1ff'
magenta = '#b5cbff'
cyan    = '#cfdeff'
white   = '#f8faff'
