-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 12,
		border_size = 1,
		resize_on_border = true,
	},
	decoration = {
		rounding = 10,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
