#!/bin/bash

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_quote=${cache_dir}/weather-quote
cache_weather_hex=${cache_dir}/weather-hex
cache_weather_icon=${cache_dir}/weather-icon

## Weather data
KEY="a008a9710a4b415f99db27500f664657"
ID="Osvaldo+Cruz,BR"
UNIT="metric" # Available options : 'metric' or 'imperial'

## Make cache dir
[[ ! -d "$cache_dir" ]] && mkdir -p "$cache_dir"

## Get data
get_weather_data() {
	weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?appid=$KEY&q=$ID&units=$UNIT")
	echo "${weather}"
	echo "Resposta do CURL: $weather" >>/tmp/debug-weather.log
	echo "DEBUG: weather=$weather" >>/tmp/weather_debug.log
	echo "DEBUG: temp=$weather_temp" >>/tmp/weather_debug.log

	if [[ -n "$weather" ]]; then
		weather_temp=$(echo "$weather" | jq ".main.temp // empty" | cut -d "." -f 1)
		weather_icon_code=$(echo "$weather" | jq -r ".weather[0].icon // empty")
		weather_description=$(echo "$weather" | jq -r ".weather[0].description // empty" | sed -e "s/\b\(.\)/\u\1/g")

		# Proteção contra campos vazios
		[[ -z "$weather_temp" ]] && weather_temp="-" || weather_temp="${weather_temp}°C"
		[[ -z "$weather_description" ]] && weather_description="Weather Unavailable"

		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d" ]; then
			weather_icon=" "
			weather_quote="Forecast says it's misty \nMake sure you don't get lost on your way..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "50n" ]; then
			weather_icon=" "
			weather_quote="Forecast says it's a misty night \nDon't go anywhere tonight or you might get lost..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "01d" ]; then
			weather_icon=" "
			weather_quote="It's a sunny day, gonna be fun! \nDon't go wandering all by yourself though..."
			weather_hex="#ffd86b"
		elif [ "$weather_icon_code" == "01n" ]; then
			weather_icon=" "
			weather_quote="It's a clear night \nYou might want to take a evening stroll to relax..."
			weather_hex="#fcdcf6"
		elif [ "$weather_icon_code" == "02d" ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "02n" ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03d" ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03n" ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04d" ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04n" ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "09d" ]; then
			weather_icon=" "
			weather_quote="It's rainy, it's a great day! \nGet some ramen and watch as the rain falls..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "09n" ]; then
			weather_icon=" "
			weather_quote=" It's gonna rain tonight it seems \nMake sure your clothes aren't still outside..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10d" ]; then
			weather_icon=" "
			weather_quote="It's rainy, it's a great day! \nGet some ramen and watch as the rain falls..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10n" ]; then
			weather_icon=" "
			weather_quote=" It's gonna rain tonight it seems \nMake sure your clothes aren't still outside..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "11d" ]; then
			weather_icon=""
			weather_quote="There's storm for forecast today \nMake sure you don't get blown away..."
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "11n" ]; then
			weather_icon=""
			weather_quote="There's gonna be storms tonight \nMake sure you're warm in bed and the windows are shut..."
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "13d" ]; then
			weather_icon=" "
			weather_quote="It's gonna snow today \nYou'd better wear thick clothes and make a snowman as well!"
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "13n" ]; then
			weather_icon=" "
			weather_quote="It's gonna snow tonight \nMake sure you get up early tomorrow to see the sights..."
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "40d" ]; then
			weather_icon=" "
			weather_quote="Forecast says it's misty \nMake sure you don't get lost on your way..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "40n" ]; then
			weather_icon=" "
			weather_quote="Forecast says it's a misty night \nDon't go anywhere tonight or you might get lost..."
			weather_hex="#84afdb"
		else
			weather_icon=" "
			weather_quote="Sort of odd, I don't know what to forecast \nMake sure you have a good time!"
			weather_hex="#adadff"
		fi
		echo "$weather_icon" >"$cache_weather_icon"
		echo "$weather_description" >"$cache_weather_stat"
		echo "$weather_temp" >"$cache_weather_degree"
		echo -e "$weather_quote" >"$cache_weather_quote"
		echo "$weather_hex" >"$cache_weather_hex"
	else
		# Em caso de erro
		echo "Weather Unavailable" >"$cache_weather_stat"
		echo " " >"$cache_weather_icon"
		echo -e "Ah well, no weather huh? \nEven if there's no weather, it's gonna be a great day!" >"$cache_weather_quote"
		echo "-" >"$cache_weather_degree"
		echo "#adadff" >"$cache_weather_hex"
	fi
}

# Verifica se os arquivos de cache existem, senão executa a coleta
if [[ ! -f "$cache_weather_icon" || ! -f "$cache_weather_stat" || ! -f "$cache_weather_degree" ]]; then
	get_weather_data
fi

# Interface CLI
case "$1" in
--icon) cat "$cache_weather_icon" ;;
--temp) cat "$cache_weather_degree" ;;
--stat) cat "$cache_weather_stat" ;;
--quote) cat "$cache_weather_quote" ;;
--quote2) echo "" ;;
--hex) cat "$cache_weather_hex" ;;
*) get_weather_data ;;
esac
